
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bikestation_development

test:
  <<: *default
  database: bikestation_test
  

production:
  <<: *default
  database: bikestation_production
  username: bikestation
  password: <%= ENV['BIKESTATION_DATABASE_PASSWORD'] %>
